sudo: false

language: perl

perl:
  - "5.22"
  - "5.24"
  - "5.26"

before_install:
  - cpanm --notest
    Devel::Cover::Report::Coveralls

script:
  - cover -test -report coveralls
  - perl Makefile.PL
  - make thirdparty
  - make
  - perl -I./thirdparty/lib/perl5/ -I./lib thirdparty/bin/mojo  generate  callbackery_app


